'use client';

import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
    Users,
    MessageSquare,
    Search,
    Filter,
    MoreHorizontal,
    Star,
    Zap,
    Tag,
    Clock,
    User,
    ArrowUpRight
} from 'lucide-react';

const leads = [
    {
        id: '1',
        userName: 'Alex Rivera',
        email: 'alex@startup.io',
        request: 'Needs a custom integration with HubSpot to sync lead scores automatically.',
        source: 'AI Lead Magnet Pro',
        status: 'Hot',
        date: '2 hours ago',
        potentialValue: '$250/mo'
    },
    {
        id: '2',
        userName: 'Sarah Chen',
        email: 'sarah.c@agency.com',
        request: 'Asking if the Notion Sync Engine can handle shared team databases with permissions.',
        source: 'Notion Sync Engine',
        status: 'Warm',
        date: '5 hours ago',
        potentialValue: '$49/mo'
    },
    {
        id: '3',
        userName: 'Jordan Smith',
        email: 'jordan@freelance.com',
        request: 'Would like to add Telegram notifications to the Gmail Triage Bot.',
        source: 'Gmail Triage Bot',
        status: 'Custom Request',
        date: '1 day ago',
        potentialValue: 'N/A'
    }
];

export default function LeadCRMPage() {
    return (
        <div className="p-6 lg:p-10 max-w-7xl mx-auto space-y-8">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div className="space-y-1">
                    <h1 className="text-3xl font-bold">Lead CRM</h1>
                    <p className="text-[var(--muted-fg)]">Requests generated by your AI Agent from potential buyers.</p>
                </div>
                <div className="flex gap-2">
                    <Badge variant="primary" className="h-9 px-4 rounded-xl border-primary-500/20 bg-primary-500/5 text-primary-400 font-bold">
                        <Users className="w-4 h-4 mr-2" /> 12 New Leads
                    </Badge>
                </div>
            </div>

            {/* Quick Stats */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                {[
                    { label: 'Total Leads', val: '142', icon: User, color: 'text-primary-400' },
                    { label: 'Conversion Rate', val: '12.4%', icon: TrendingUp, color: 'text-emerald-400' },
                    { label: 'Custom Requests', val: '28', icon: MessageSquare, color: 'text-amber-400' },
                    { label: 'Pipe Value', val: '$2,400', icon: DollarSign, color: 'text-accent-400' },
                ].map(s => (
                    <Card key={s.label} className="p-4 flex items-center gap-3 border-none bg-gradient-to-br from-[var(--card)] to-[var(--muted)]">
                        <div className={`p-2 rounded-lg bg-[var(--card)] ${s.color}`}>
                            <s.icon className="w-5 h-5" />
                        </div>
                        <div>
                            <p className="text-[10px] uppercase font-bold text-[var(--muted-fg)]">{s.label}</p>
                            <p className="text-xl font-black">{s.val}</p>
                        </div>
                    </Card>
                ))}
            </div>

            {/* Main CRM Table/List */}
            <Card className="p-0 overflow-hidden">
                <div className="p-4 border-b border-[var(--border)] bg-[var(--muted)]/30 flex items-center justify-between gap-4">
                    <div className="relative flex-1 max-w-md">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[var(--muted-fg)]" />
                        <input
                            type="text"
                            placeholder="Search leads, requests, or users..."
                            className="w-full bg-transparent border-none pl-10 pr-4 py-2 text-sm focus:ring-0"
                        />
                    </div>
                    <div className="flex gap-2">
                        <Button variant="outline" size="sm" className="rounded-xl h-9">
                            <Filter className="w-4 h-4 mr-1.5" /> Filter
                        </Button>
                        <Button variant="outline" size="sm" className="rounded-xl h-9">
                            Export
                        </Button>
                    </div>
                </div>

                <div className="divide-y divide-[var(--border)]">
                    {leads.map((lead) => (
                        <div key={lead.id} className="p-6 hover:bg-[var(--muted)]/20 transition-all group">
                            <div className="flex flex-col lg:flex-row gap-6">
                                {/* Lead Meta */}
                                <div className="flex-1 space-y-3">
                                    <div className="flex items-center justify-between">
                                        <div className="flex items-center gap-3">
                                            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary-500/20 to-accent-500/20 flex items-center justify-center text-primary-400 font-bold border border-primary-500/20">
                                                {lead.userName.charAt(0)}
                                            </div>
                                            <div>
                                                <h3 className="font-bold text-[var(--fg)] group-hover:text-primary-400 transition-colors uppercase tracking-tight">{lead.userName}</h3>
                                                <p className="text-xs text-[var(--muted-fg)]">{lead.email}</p>
                                            </div>
                                        </div>
                                        <Badge
                                            variant={lead.status === 'Hot' ? 'error' : lead.status === 'Warm' ? 'warning' : 'primary'}
                                            className="font-black italic uppercase text-[9px] px-2"
                                            pulse={lead.status === 'Hot'}
                                        >
                                            {lead.status}
                                        </Badge>
                                    </div>

                                    <div className="bg-[var(--muted)]/50 rounded-xl p-4 border border-[var(--border)]">
                                        <p className="text-sm text-[var(--fg)] leading-relaxed italic">
                                            "{lead.request}"
                                        </p>
                                    </div>
                                </div>

                                {/* Details & Actions */}
                                <div className="flex flex-row lg:flex-col justify-between lg:w-64 border-l border-[var(--border)] lg:pl-6 space-y-4">
                                    <div className="space-y-4">
                                        <div>
                                            <p className="text-[10px] uppercase font-bold text-[var(--muted-fg)] tracking-widest mb-1 flex items-center gap-1">
                                                <Tag className="w-3 h-3" /> Source Automation
                                            </p>
                                            <p className="text-xs font-bold truncate text-primary-400 underline decoration-primary-500/20">{lead.source}</p>
                                        </div>
                                        <div>
                                            <p className="text-[10px] uppercase font-bold text-[var(--muted-fg)] tracking-widest mb-1 flex items-center gap-1">
                                                <ArrowUpRight className="w-3 h-3 text-emerald-400" /> Potential
                                            </p>
                                            <p className="text-sm font-black">{lead.potentialValue}</p>
                                        </div>
                                    </div>

                                    <div className="flex gap-2 items-end">
                                        <Button size="sm" className="rounded-lg flex-1 font-bold italic uppercase h-9">
                                            Reply
                                        </Button>
                                        <Button variant="secondary" size="icon" className="h-9 w-9 rounded-lg">
                                            <MoreHorizontal className="w-4 h-4" />
                                        </Button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </Card>

            <div className="text-center p-8 bg-gradient-to-r from-primary-500/5 to-accent-500/5 rounded-3xl border border-primary-500/10">
                <p className="text-xs text-[var(--muted-fg)] font-bold uppercase tracking-[0.2em] mb-2">Pro Tip</p>
                <p className="text-sm text-[var(--fg)] max-w-lg mx-auto italic">
                    "AI agents categorize leads based on intent. Hot leads have expressed immediate purchase intent or specific integration needs."
                </p>
            </div>
        </div>
    );
}

const DollarSign = ({ className }: { className?: string }) => (
    <span className={className}>$</span>
);

const TrendingUp = ({ className }: { className?: string }) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24" height="24" viewBox="0 0 24 24"
        fill="none" stroke="currentColor" strokeWidth="2"
        strokeLinecap="round" strokeLinejoin="round"
        className={className}
    >
        <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline>
        <polyline points="17 6 23 6 23 12"></polyline>
    </svg>
);
